### ISSUE TITLE
“旧”字的左右平衡问题

### ISSUE THREAD

**Issue by PaPerseller** [max32002/swei-sans#1]
“旧”字右边“日”被拔脚后，左边的原长度一竖旁就显得略长，整体观感有些失衡。

**Comment by max32002** [comment]
這個解法有很多個，但立竿見影、不動腦筋、最花時間的片面解法：
https://github.com/max32002/swei-gothic/issues/1

應該是可以使用程式來解決，但似乎需要動動腦。

**Comment by max32002** [comment]
![Screen Shot 2020-07-27 at 19 23 43](https://user-images.githubusercontent.com/4498233/88536683-d519a980-d03e-11ea-9eef-70853ae359f2.png)
拔腳後懸空的感覺很不平衡，目前其他拔腳的字型（未来荧黑和源泉圆体），也還沒有解決這一個問題。

**Comment by PaPerseller** [comment]
对比了下同样拔脚的oppo sans，也未解决此问题
