### ISSUE TITLE
Bold 的版本與其他字重的命名不同（主要是 Family）導致應用不便

### ISSUE THREAD

**Issue by MadMaxChow** [max32002/swei-sans#2]
Bold 的 `Family` 是 `Swei Sans CJK SC`，其他的都是 `獅尾黑體SC`
建議盡快重新生成～，謝謝你的分享

**Comment by max32002** [comment]
好像解決了，請再幫我測試看看，如果還有問題，請再幫我留言，謝謝。

**Comment by MadMaxChow** [comment]
下载太慢，一起没有成功。你有在gitee上提供镜像吗



------------------ 原始邮件 ------------------

**Comment by MadMaxChow** [comment]
已解决，谢谢！

------------------ 原始邮件 ------------------
